In [16]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense, LSTM
import tensorflow as tf

x = array([[1, 2, 3],[2, 3, 4],[3, 4, 5],[4, 5, 6]])
y = array([4, 5, 6, 7])

print('x shape : ', x.shape)
print('y shape : ', y.shape)

x shape :  (4, 3)
y shape :  (4,)


In [17]:
print(x)
print('-------x reshape-----------')
x = x.reshape((x.shape[0], x.shape[1], 1))
print('x shape : ', x.shape)
print(x)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
-------x reshape-----------
x shape :  (4, 3, 1)
[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]]


In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D, LSTM

In [23]:
model = Sequential()
model.add(LSTM(40, activation="relu", input_shape=(3,1)))
# DENSE와 사용법 동일하나 input_shape=(열, 몇개씩잘라작업)
model.add(Dense(5))
model.add(Dense(1))
 
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 40)                6720      
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 205       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 6         
Total params: 6,931
Trainable params: 6,931
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=100, batch_size=1)

x_input = array([6,7,8])
x_input = x_input.reshape((1,3,1))
 
yhat = model.predict(x_input)
print(yhat)

Epoch 1/100
4/4 [==============================] - 0s 1ms/step - loss: 31.9799
Epoch 2/100
4/4 [==============================] - 0s 1ms/step - loss: 28.5877
Epoch 3/100
4/4 [==============================] - 0s 1ms/step - loss: 25.5737
Epoch 4/100
4/4 [==============================] - 0s 1ms/step - loss: 22.6358
Epoch 5/100
4/4 [==============================] - 0s 1ms/step - loss: 19.9559
Epoch 6/100
4/4 [==============================] - 0s 1ms/step - loss: 17.6015
Epoch 7/100
4/4 [==============================] - 0s 1ms/step - loss: 15.0705
Epoch 8/100
4/4 [==============================] - 0s 1ms/step - loss: 12.1661
Epoch 9/100
4/4 [==============================] - 0s 1ms/step - loss: 9.8063
Epoch 10/100
4/4 [==============================] - 0s 1ms/step - loss: 7.3599
Epoch 11/100
4/4 [==============================] - 0s 1ms/step - loss: 5.1124
Epoch 12/100
4/4 [==============================] - 0s 1ms/step - loss: 3.3460
Epoch 13/100
4/4 [==============================] - 0